In [35]:
import numpy as np


In [4]:
a=[1,2,3,4]
arr=np.array(a)
print(arr)
print(type(arr))
print(a)

[1 2 3 4]
<class 'numpy.ndarray'>
[1, 2, 3, 4]


In [4]:
#dono a or b main list same amount ki honi chahiya means a main 3 values rakhi hai to b main bhi 3 hi rakhni hai 
import numpy as np
a=[1,2,3]
b=[4,5,6]
arr= np.array([a,b])
print(arr)

[[1 2 3]
 [4 5 6]]


In [14]:
# in this it print five time zero
a=np.zeros(5)
print(a)
#garbage value
b=np.empty(5)
print(b)
# in this we print five time 1
c=np.ones(5)
print(c)
# in this frist is start mean start from thw 2 and end with the 10 and last one is for the space
d=np.linspace(2,10,2) 
print(d)
# in this frist is start mean start from thw 2 and end with the 10 and last one is for the jump
f=np.arange(2,10,2)
print(f)

[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[ 2. 10.]
[2 4 6 8]


In [21]:
# a=[1,2,3,4]
# b=[5,6,7,8]
# np.ones((len(a),len(b)))
a=np.ones((4,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
a=[1,2,3,4]
b=[4,5,6,7]
arr1=np.array(a)
arr2=np.array(b)
c=arr1+arr2
print(c)

[ 5  7  9 11]


In [25]:
a=[1,2,3,4,5,6,7,8,9,10]
np.arange(3,10,3)

array([3, 6, 9])

In [26]:
c=[1,2,3,4,5]
np.linspace(2,5,3)

array([2. , 3.5, 5. ])

In [27]:
import random

In [28]:
np.random.rand(5) #rand give the random value between 0 and 1

array([0.42449826, 0.12724661, 0.97755068, 0.59803665, 0.45967582])

In [29]:
np.random.ranf(5)

array([0.51577045, 0.40446948, 0.80704481, 0.8513342 , 0.71852815])

In [30]:
np.random.randn(5)

array([-1.42259876,  1.08514822, -0.7347992 , -0.51396069, -0.35931617])

In [34]:
np.random.randint(2,10,6)#2 start ho 10 per end ho ga or 6 random values deni hai

array([2, 5, 5, 4, 4, 9], dtype=int32)

# dimensions

In [7]:
#1d
a=[[[1,2,3,4]]]
arr=np.array(a)
print(arr)
print(arr.ndim)#ndim is use to tell us what is the dimension


[[[1 2 3 4]]]
3


In [37]:
#2d
a=[[1,2,3],[4,5,6]]
arr=np.array(a)
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [6]:
#3d
a=[[[1,2,3],[4,5,6],[7,8,9]]]
arr=np.array(a)
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [46]:
#nd many dimensions no exist
a=[1,2,3,4]
arr=np.array(a,ndmin=5)
print(arr)
print(arr.ndim)


[[[[[1 2 3 4]]]]]
5


In [52]:
#attributes
a=[[1,2,3],[4,5,6]]
arr=np.array(a)
print(arr.ndim)
print(arr.size)#number btay ga 
print(arr.dtype)
print(arr.shape)#tell rows and column
#function
print(arr.min())#sb sy chota no
print(arr .max())#sb sy bara no
print(arr.argmin())#tell the index number of small value
print(arr.argmax())#tell the index value of large value
print(arr.reshape(3,2))

2
6
int64
(2, 3)
1
6
0
5
[[1 2]
 [3 4]
 [5 6]]
