In [4]:
import numpy as np
# a=[1,2,3,4,5,6]
# b=np.copy(a)
# print(b)
# c=np.append(a,4)#add number at last
# print(c)
# d=np.insert(a,1,45)
# print(d)
# e=np.delete(a,2)
# print(e)
# a=[1,2,3,4,5,6]
# f=np.split(a,2)
# print(f)
aa = np.array([1,2,3,4,5,6])
f = np.split(aa, 2)
print(f)
# a=[1,2]
# b=[3,4]
# np.array(a)
# np.array(b)
# np.concatenate((a,b))

[array([1, 2, 3]), array([4, 5, 6])]


# practice numpy 1 

In [13]:
a=[1,2,3,4,5]
arr=np.array(a)
print(arr)

[1 2 3 4 5]


In [16]:
#2
np.arange(1,21,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [30]:
#3
import numpy as np
a=[1,2,3,4,5,6]
arr=np.array(a)
b=arr.reshape(2,3)
print(b)
# a = np.array([1, 2, 3, 4, 5, 6])
# b = a.reshape(2, 3)

# print(b)

[[1 2 3]
 [4 5 6]]


In [29]:
#4
a=[1,2,3,4]
arr=np.array(a)
print(arr)
b=arr.max()
print(b)
c=arr.argmax()
print(c)

[1 2 3 4]
4
3


# saving and loadinig of numpy array

In [2]:
import numpy as np

arr=np.array([1,2,3,4])
np.save("data.npy",arr)
np.load("data.npy")

array([1, 2, 3, 4])

In [5]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.savez("multiple.npz",a=a,b=b)
data=np.load("multiple.npz")
print(data["a"])
print(data["b"] )     

[1 2 3 4]
[5 6 7 8]


In [17]:
a=[[1,2,3,4],[5,6,7,8],[1,3,7,9]]
arr=np.array(a)
print(arr)
print(arr[1,2])# 1 row and  or 2 column
print(arr[1])
print(arr[:,1])# row sari remove kerdeni hai or 1 column wali line dy ga
print(arr[1:3,1:3])

[[1 2 3 4]
 [5 6 7 8]
 [1 3 7 9]]
7
[5 6 7 8]
[2 6 3]
[[6 7]
 [3 7]]


In [18]:
arr=np.array([10,20,30,40])
arr>20

array([False, False,  True,  True])

In [19]:
arr[arr>20]#filtering

array([30, 40])

In [20]:
#broadcasting
arr=np.array([1,2,3])
arr+5

array([6, 7, 8])

In [21]:
#2d broadcasting
arr=np.array([[1,2,3],
             [4,5,6]])
arr+np.array([10,20,30])

array([[11, 22, 33],
       [14, 25, 36]])

In [26]:
import numpy as np

# # Take input from user (space separated numbers)
# user = input("Enter numbers : ")

# # Convert input string into list of integers
# st = list(map(int, user.split()))

# # Convert list into NumPy array
# arr = np.array(st)

# print("List:", st)
# print("NumPy Array:", arr)
user=input("enter number")
st=list(map(int,user.split()))
arr=np.array(st)
print(arr)

enter number 1 2 3 4


[1 2 3 4]


# practice numpy 2

In [5]:

#1
arr=np.array([1,2,3,4,5,6,7,8,9])
b=arr.reshape(3,3)
print(b)
#2
print(b[1])
#3
b[b>5]
#4
b+10
#5


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]


array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])