# typecasting

In [1]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr.dtype)

int64


In [4]:
arr=arr.astype(float)
print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float64


In [13]:
arr=np.array([2.3,3.3,4.3,4.5])
arr=arr.astype(int)
print(arr)

[2 3 4 4]


# arthimetic operation

In [14]:
a=np.array([4,5,6])
b=np.array([7,8,9])
a+b

array([11, 13, 15])

In [17]:
a/b

array([0.57142857, 0.625     , 0.66666667])

In [18]:
a**2

array([16, 25, 36])

In [19]:
a-b

array([-3, -3, -3])

In [20]:
a*b

array([28, 40, 54])

# universal function

In [23]:
arr = np.array([1,4,9,16])
np.sqrt(arr)


array([1., 2., 3., 4.])

In [24]:
np.exp(arr)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06])

In [25]:
np.sin(arr)

array([ 0.84147098, -0.7568025 ,  0.41211849, -0.28790332])

In [26]:
np.abs(np.array([-1,-2,-3]))

array([1, 2, 3])

# practice numpy 3

In [8]:
#1 
arr=np.array([1,2,3,4])
arr=arr.astype(float)
print(arr)

[1. 2. 3. 4.]


In [9]:
#2
a=np.array([1,2,3])
b=np.array([4,5,6])
a*b

array([ 4, 10, 18])

In [10]:
#3
a=np.array([1,2,3])
a**2

array([1, 4, 9])

In [11]:
#4
a=np.array([1,2,3])
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [12]:
#5
a=np.array([1,2,3])
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

# matrix practice

In [36]:
# practice
# 1
a=np.array([[1,2],[4,5]])
print(a)

[[1 2]
 [4 5]]


In [37]:
#2 
a=[1,2,3]
b=[4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

In [42]:
#3
a=[[1,2],
   [3,4]]
b=[[4,5],
   [6,7]]
print(np.dot(a,b))

[[16 19]
 [36 43]]


In [48]:
#4
# a=np.array([[1,2,3,4],
#           [5,6,7,8]])
a=np.array([[1,2,3]])
print(a.T)

[[1]
 [2]
 [3]]


In [46]:
#5
a=np.random.randn(3,3)
print(a)

[[ 0.01865875 -1.55846064 -0.81293169]
 [ 0.05663413 -0.316863   -0.29760941]
 [-0.51337839  0.19486218 -2.0959744 ]]
